//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ThanhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThanhVien()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.KhachHangs = new HashSet<KhachHang>();
        }
    
        public int MaTV { get; set; }
        [Required(ErrorMessage = "Nhap vao ten tai khoan !")]
        public string TaiKhoan { get; set; }
        [Required(ErrorMessage = "Nhap vao mat khau !")]
        public string MatKhau { get; set; }
        [Required(ErrorMessage = "Nhap vao ho va ten !")]
        public string HoTen { get; set; }
        public string DiaChi { get; set; }
        [Required(ErrorMessage = "Nhap vao so dien thoai !")]
        public string SoDienThoai { get; set; }
        [Required(ErrorMessage = "Nhap vao Email !")]
        public string Email { get; set; }
        public Nullable<int> MaLTV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachHang> KhachHangs { get; set; }
        public virtual LoaiThanhVien LoaiThanhVien { get; set; }
    }
}
